name: CI Pipeline

on:
  push:
    branches:
       - '**'
  workflow_dispatch:

jobs:
  lint:
    name: PHP Lint Check
    runs-on: ubuntu-latest
    container: php:8.0
    steps:
      - uses: actions/checkout@v3

      - name: Run PHP Syntax Check
        run: |
          echo "Running PHP lint check..."
          find wp-content -type f -name "*.php" -print0 | while IFS= read -r -d '' file; do
            php -l "$file" || exit 1
          done
          echo "No PHP syntax errors found âœ…"

  deploy-staging:
    name: Deploy to Staging
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    needs: lint
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}

      - name: Add WP Engine to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H git.wpengine.com >> ~/.ssh/known_hosts

      - name: Git config
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Push to STAGING
        run: git push -v ${{ vars.STAGING_REMOTE }} HEAD --force

  deploy-production:
    name: Deploy to Production
    if: github.ref == 'refs/heads/master' && github.event_name == 'workflow_dispatch'
    needs: lint
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}

      - name: Git config
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Push to PRODUCTION
        run: git push -v ${{ vars.PRODUCTION_REMOTE }} HEAD --force
